development:
  adapter: postgresql
  database: recipe_app_dev
  host: localhost
  pool: 5
  timeout: 5000

production:
  # url: <%= ENV['DATABASE_URL'] %>
  adapter: postgresql
  database: recipe_app
  host: localhost 
  pool: 5
  timeout: 5000

test:
  adapter: sqlite3
  database: recipe_app_test
  host: localhost 
  pool: 5
  timeout: 5000